const IMG_BASE_URL =
  'https://tcgwvzqiygfpmcrovgzl.supabase.co/storage/v1/object/public/foods-pics/';

type Food = {
  name: string;
  categoryId: string;
  imageUrl: string;
  calories: number;
  price: number;
  quantity: number;
};

enum Categories {
  chicken = '0aa3ed9a-c173-4340-b6c7-4b4fb5a5a1cc',
  curry = 'a3a2dc14-9464-4537-8969-27e671ac761a',
  icecream = 'bca39133-25e1-4e38-ba34-22821d8e0773',
  fruit = '8ab07931-e33b-42c9-a02b-50835e5c7f33',
  drink = '7a1eec6c-8360-4a4a-9c38-277a1c761354',
  fish = '3fba8e02-b725-481b-b0d8-c947bad6c600',
  rice = 'b23f5fb4-4d38-46f8-92d8-fb6ecfda96db',
}

export const initialFoods: Food[] = [
  {
    name: 'Grilled Chicken Tacos',
    categoryId: Categories.chicken,
    imageUrl: IMG_BASE_URL + 'c7.webp',
    calories: 275,
    price: 29,
    quantity: 0,
  },
  {
    name: 'Mega Truffle',
    categoryId: Categories.icecream,
    imageUrl: IMG_BASE_URL + 'i1.webp',
    calories: 243,
    price: 13,
    quantity: 0,
  },
  {
    name: 'Pepsi',
    categoryId: Categories.drink,
    imageUrl: IMG_BASE_URL + 'd2.webp',
    calories: 112,
    price: 9,
    quantity: 0,
  },
  {
    name: 'Green Curry',
    categoryId: Categories.chicken,
    imageUrl: IMG_BASE_URL + 'cu6.webp',
    calories: 206,
    price: 14,
    quantity: 0,
  },
  {
    name: 'Greek Chicken Bowls',
    categoryId: Categories.chicken,
    imageUrl: IMG_BASE_URL + 'c3.webp',
    calories: 385,
    price: 29,
    quantity: 0,
  },
  {
    name: 'Watermelon',
    categoryId: Categories.fruit,
    imageUrl: IMG_BASE_URL + 'f10.webp',
    calories: 30,
    price: 7,
    quantity: 0,
  },
  {
    name: 'Pomegranate',
    categoryId: Categories.fruit,
    imageUrl: IMG_BASE_URL + 'f6.webp',
    calories: 68,
    price: 12,
    quantity: 0,
  },
  {
    name: 'Asian Tilapia',
    categoryId: Categories.fish,
    imageUrl: IMG_BASE_URL + 'fi2.webp',
    calories: 212,
    price: 28,
    quantity: 0,
  },
  {
    name: 'Spinach Rice',
    categoryId: Categories.rice,
    imageUrl: IMG_BASE_URL + 'r2.webp',
    calories: 325,
    price: 24,
    quantity: 0,
  },
  {
    name: 'Pineapple',
    categoryId: Categories.fruit,
    imageUrl: IMG_BASE_URL + 'f2.webp',
    calories: 50,
    price: 12,
    quantity: 0,
  },
  {
    name: 'Japanese Beef Curry',
    categoryId: Categories.curry,
    imageUrl: IMG_BASE_URL + 'cu1.webp',
    calories: 341,
    price: 19,
    quantity: 0,
  },
  {
    name: 'Golden Tofu Curry',
    categoryId: Categories.curry,
    imageUrl: IMG_BASE_URL + 'cu4.webp',
    calories: 498,
    price: 30,
    quantity: 0,
  },
  {
    name: 'Alaskan Cod Chowder',
    categoryId: Categories.fish,
    imageUrl: IMG_BASE_URL + 'fi3.webp',
    calories: 270,
    price: 35,
    quantity: 0,
  },
  {
    name: 'Chana Saag Curry',
    categoryId: Categories.curry,
    imageUrl: IMG_BASE_URL + 'cu5.webp',
    calories: 360,
    price: 21,
    quantity: 0,
  },
  {
    name: 'Bournville',
    categoryId: Categories.icecream,
    imageUrl: IMG_BASE_URL + 'i2.webp',
    calories: 315,
    price: 12,
    quantity: 0,
  },
  {
    name: 'Skinny Teriyaki Chicken',
    categoryId: Categories.chicken,
    imageUrl: IMG_BASE_URL + 'c2.webp',
    calories: 203,
    price: 23,
    quantity: 0,
  },
  {
    name: 'Chicken Florentine',
    categoryId: Categories.chicken,
    imageUrl: IMG_BASE_URL + 'c6.webp',
    calories: 295,
    price: 26.5,
    quantity: 0,
  },
  {
    name: 'Coca Cola',
    categoryId: Categories.drink,
    imageUrl: IMG_BASE_URL + 'd8.webp',
    calories: 108,
    price: 8,
    quantity: 0,
  },
  {
    name: 'RedBull',
    categoryId: Categories.drink,
    imageUrl: IMG_BASE_URL + 'd1.webp',
    calories: 100,
    price: 8,
    quantity: 0,
  },
  {
    name: 'Banana',
    categoryId: Categories.fruit,
    imageUrl: IMG_BASE_URL + 'f9.webp',
    calories: 89,
    price: 9,
    quantity: 0,
  },
  {
    name: 'Tilapia with Jasmine Rice',
    categoryId: Categories.rice,
    imageUrl: IMG_BASE_URL + 'r3.webp',
    calories: 412,
    price: 34,
    quantity: 0,
  },
  {
    name: 'Baked Fish Tacos',
    categoryId: Categories.fish,
    imageUrl: IMG_BASE_URL + 'fi1.webp',
    calories: 296,
    price: 33,
    quantity: 0,
  },
  {
    name: 'Strawberry',
    categoryId: Categories.fruit,
    imageUrl: IMG_BASE_URL + 'f1.webp',
    calories: 59,
    price: 8,
    quantity: 0,
  },
  {
    name: 'Blackberry',
    categoryId: Categories.fruit,
    imageUrl: IMG_BASE_URL + 'f3.webp',
    calories: 43,
    price: 7,
    quantity: 0,
  },
  {
    name: 'Monster Energy',
    categoryId: Categories.drink,
    imageUrl: IMG_BASE_URL + 'd3.webp',
    calories: 158,
    price: 13,
    quantity: 0,
  },
  {
    name: 'Chicken Curry',
    categoryId: Categories.curry,
    imageUrl: IMG_BASE_URL + 'cu3.webp',
    calories: 420,
    price: 32,
    quantity: 0,
  },
  {
    name: 'Chicken Riggies',
    categoryId: Categories.chicken,
    imageUrl: IMG_BASE_URL + 'c1.webp',
    calories: 340,
    price: 23,
    quantity: 0,
  },
  {
    name: 'Uva Negra',
    categoryId: Categories.fruit,
    imageUrl: IMG_BASE_URL + 'f4.webp',
    calories: 68,
    price: 11,
    quantity: 0,
  },
  {
    name: 'Lemon Rice Pilaf',
    categoryId: Categories.rice,
    imageUrl: IMG_BASE_URL + 'r1.webp',
    calories: 213,
    price: 19,
    quantity: 0,
  },
];
