import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import StoreProvider from '@/components/StoreProvider';
import { ThemeProvider } from '@/components/ThemeProvider';

import Header from './_components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'QuickBite',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <StoreProvider>
        <body className={`mx-auto w-11/12 max-w-5xl ${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main>{children}</main>
          </ThemeProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
